// Fill out your copyright notice in the Description page of Project Settings.


#include "UI/Widget/ActorObjectInfo/SDLGZWidget.h"
#include "SlateOptMacros.h"
#include "UI/Style/LFSStyle.h"
#include "UI/Style/MainSlateWidgetStyle.h"
#include "UI/Widget/SLFSProgressbar.h"
#include "UI/Widget/Main/Left/SHuanWidget.h"
#include "Widgets/Images/SImage.h"
#include "Widgets/Layout/SUniformGridPanel.h"

BEGIN_SLATE_FUNCTION_BUILD_OPTIMIZATION
void SDLGZWidget::Construct(const FArguments& InArgs)
{
	MainStyle=&LFSStyle::Get().GetWidgetStyle<FMainSlateStyle>("BPMainStyle");
	
	ChildSlot
	[
		// Populate the widget
		SNew(SBox)
		[
			SNew(SOverlay)
			+SOverlay::Slot()
			.HAlign(HAlign_Fill)
			.VAlign(VAlign_Fill)
			[
				SNew(SImage)
				.Image(&MainStyle->Center_Window4)
			]
			+SOverlay::Slot()
			.Padding(FMargin(30.0f))
			[
				SNew(SBorder)
				[
					SNew(SVerticalBox)
					+SVerticalBox::Slot()
					.AutoHeight()
					[
						SNew(SHorizontalBox)
						+SHorizontalBox::Slot()
						.AutoWidth()
						[
							SNew(SBorder)
							[
								SNew(STextBlock)
								.Font(MainStyle->FontInfo_Size_12_White)
								.Text(FText::FromString(TEXT("感知电缆段")))
							]	
						]
						+SHorizontalBox::Slot()
						[
							SNew(SBorder)
							[
								SNew(STextBlock)
								.Font(MainStyle->FontInfo_Size_12_White)
								.Text(FText::FromString(TEXT("临江门变电站648开关至来福士广场公共开闭所")))
							]
						]
					]
					+SVerticalBox::Slot()
					.AutoHeight()
					[
						SNew(SBorder)
						[
							SNew(SOverlay)
							+SOverlay::Slot()
							[
								SNew(SImage)
								.Image(&MainStyle->ProbarFillImageBrush)
							]
							+SOverlay::Slot()
							.HAlign(HAlign_Center)
							.VAlign(VAlign_Center)
							[
								SNew(STextBlock)
								.Font(MainStyle->FontInfo_Size_12_White)
								.Text(FText::FromString(TEXT("电缆绝缘在线感知")))
							]
						]
					]
					+SVerticalBox::Slot()
					.AutoHeight()
					[
						SNew(SBorder)
						[
							SNew(SHorizontalBox)
							+SHorizontalBox::Slot()
							[
								SNew(STextBlock)
								.Font(MainStyle->FontInfo_Size_12_White)
								.Text(FText::FromString(TEXT("电缆绝缘评价")))	
							]
							+SHorizontalBox::Slot()
							.AutoWidth()
							[
								SNew(SBorder)
								[
									SNew(STextBlock)
									.Font(MainStyle->FontInfo_Size_12_White)
									.Text(FText::FromString(TEXT("正常")))
								]
							]
						]
					]
					+SVerticalBox::Slot()
					.AutoHeight()
					[
						SNew(STextBlock)
						.Font(MainStyle->FontInfo_Size_12_White)
						.Text(FText::FromString(TEXT("两端电流差值")))
					]
					+SVerticalBox::Slot()
					.AutoHeight()
					[
						SNew(SHorizontalBox)
						+SHorizontalBox::Slot()
						[
							SNew(SHorizontalBox)
							+SHorizontalBox::Slot()
							.AutoWidth()
							[
								SNew(STextBlock)
								.Font(MainStyle->FontInfo_Size_12_White)
								.Text(FText::FromString(TEXT("A相")))
							]
							+SHorizontalBox::Slot()
							[
								SAssignNew(Progressbar_A,SLFSProgressbar)
								.percent(0.13)
								//.Name(FText::FromString(TEXT("0.13A")))
							]
						]
						+SHorizontalBox::Slot()
						.Padding(FMargin(10,0,0,0))
						[
							SNew(SHorizontalBox)
							+SHorizontalBox::Slot()
							.AutoWidth()
							[
								SNew(STextBlock)
								.Font(MainStyle->FontInfo_Size_12_White)
								.Text(FText::FromString(TEXT("B相")))
							]
							+SHorizontalBox::Slot()
							[
								SAssignNew(Progressbar_B,SLFSProgressbar)
								.percent(0.13)
								//.Name(FText::FromString(TEXT("0.13A")))
							]
						]
						+SHorizontalBox::Slot()
						.Padding(FMargin(10,0,10,0))
						[
							SNew(SHorizontalBox)
							+SHorizontalBox::Slot()
							.AutoWidth()
							[
								SNew(STextBlock)
								.Font(MainStyle->FontInfo_Size_12_White)
								.Text(FText::FromString(TEXT("C相")))
							]
							+SHorizontalBox::Slot()
							[
								SAssignNew(Progressbar_A,SLFSProgressbar)
								.percent(0.27)
								//.Name(FText::FromString(TEXT("0.27A")))
							]
						]
					]
					+SVerticalBox::Slot()
					.AutoHeight()
					.Padding(FMargin(0,5,0,0))
					[
						SNew(SBorder)
						[
							SNew(SOverlay)
							+SOverlay::Slot()
							[
								SNew(SImage)
								.Image(&MainStyle->ProbarFillImageBrush)
							]
							+SOverlay::Slot()
							.HAlign(HAlign_Center)
							.VAlign(VAlign_Center)
							[
								SNew(STextBlock)
								.Font(MainStyle->FontInfo_Size_12_White)
								.Text(FText::FromString(TEXT("接头温度感知")))
							]
						]
					]
					+SVerticalBox::Slot()
					.AutoHeight()
					[
						SNew(SBorder)
						[
							SNew(SHorizontalBox)
							+SHorizontalBox::Slot()
							[
								SNew(STextBlock)
								.Font(MainStyle->FontInfo_Size_12_White)
								.Text(FText::FromString(TEXT("电缆接头温度评价")))	
							]
							+SHorizontalBox::Slot()
							.AutoWidth()
							[
								SNew(STextBlock)
								.Font(MainStyle->FontInfo_Size_12_White)
								.Text(FText::FromString(TEXT("正常")))	
							]
						]
					]
					+SVerticalBox::Slot()
					.AutoHeight()
					[
						SNew(SBorder)
						[
							SAssignNew(WD_GridPanel,SUniformGridPanel)
							.SlotPadding(5.0F)
						]
						
					]
					+SVerticalBox::Slot()
					.AutoHeight()
					[
						SNew(SOverlay)
						+SOverlay::Slot()
						[
							SNew(SImage)
							.Image(&MainStyle->ProbarFillImageBrush)
						]
						+SOverlay::Slot()
						.HAlign(HAlign_Center)
						.VAlign(VAlign_Center)
						[
							SNew(STextBlock)
							.Font(MainStyle->FontInfo_Size_12_White)
							.Text(FText::FromString(TEXT("电缆震动感知")))
						]
					]
					+SVerticalBox::Slot()
					.AutoHeight()
					[
						SNew(SBorder)
						[	
							SNew(SHorizontalBox)
							+SHorizontalBox::Slot()
							[
								SNew(STextBlock)
								.Font(MainStyle->FontInfo_Size_12_White)
								.Text(FText::FromString(TEXT("各电缆井位电缆震动感知")))	
							]
							+SHorizontalBox::Slot()
							.AutoWidth()
							[
								SNew(SBorder)
								[
									SNew(STextBlock)
									.Font(MainStyle->FontInfo_Size_12_White)
									.Text(FText::FromString(TEXT("正常")))
								]	
							]
						]
						
					]
				]
			]
		]
	];
	if (WD_GridPanel)
	{
		WD_GridPanel->AddSlot(0,0)
		[
			SNew(SOverlay)
			+SOverlay::Slot()
			[
				SNew(SVerticalBox)
				+SVerticalBox::Slot()
				.HAlign(HAlign_Center)
				.VAlign(VAlign_Center)
				.AutoHeight()
				[
					SNew(STextBlock)
					.Font(MainStyle->FontInfo_Size_12_White)
					.Text(FText::FromString(TEXT("电缆1")))
				]
				+SVerticalBox::Slot()
				.AutoHeight()
				[
					SAssignNew(DL_1,SHuanWidget)
					.number(0.325f)
					//.Name(TEXT("烟感"))
				]
			]	
		];
		WD_GridPanel->AddSlot(1,0)
		[
			SNew(SOverlay)
			+SOverlay::Slot()
			[
				SNew(SVerticalBox)
				+SVerticalBox::Slot()
				.HAlign(HAlign_Center)
				.VAlign(VAlign_Center)
				.AutoHeight()
				[
					SNew(STextBlock)
					.Font(MainStyle->FontInfo_Size_12_White)
					.Text(FText::FromString(TEXT("电缆2")))
				]
				+SVerticalBox::Slot()
				.AutoHeight()
				[
					SAssignNew(DL_2,SHuanWidget)
					.number(0.341f)
					//.Name(TEXT("烟感"))
				]
			]	
		];
		WD_GridPanel->AddSlot(2,0)
		[
			SNew(SOverlay)
			+SOverlay::Slot()
			[
				SNew(SVerticalBox)
				+SVerticalBox::Slot()
				.HAlign(HAlign_Center)
				.VAlign(VAlign_Center)
				.AutoHeight()
				[
					SNew(STextBlock)
					.Font(MainStyle->FontInfo_Size_12_White)
					.Text(FText::FromString(TEXT("电缆3")))
				]
				+SVerticalBox::Slot()
				.AutoHeight()
				[
					SAssignNew(DL_3,SHuanWidget)
					.number(0.337f)
					//.Name(TEXT("烟感"))
				]
			]	
		];
		WD_GridPanel->AddSlot(0,1)
		[
			SNew(SOverlay)
			+SOverlay::Slot()
			[
				SNew(SVerticalBox)
				+SVerticalBox::Slot()
				.HAlign(HAlign_Center)
				.VAlign(VAlign_Center)
				.AutoHeight()
				[
					SNew(STextBlock)
					.Font(MainStyle->FontInfo_Size_12_White)
					.Text(FText::FromString(TEXT("电缆4")))
				]
				+SVerticalBox::Slot()
				.AutoHeight()
				[
					SAssignNew(DL_4,SHuanWidget)
					.number(0.332f)
					//.Name(TEXT("烟感"))
				]
			]	
		];
		WD_GridPanel->AddSlot(1,1)
		[
			SNew(SOverlay)
			+SOverlay::Slot()
			[
				SNew(SVerticalBox)
				+SVerticalBox::Slot()
				.HAlign(HAlign_Center)
				.VAlign(VAlign_Center)
				.AutoHeight()
				[
					SNew(STextBlock)
					.Font(MainStyle->FontInfo_Size_12_White)
					.Text(FText::FromString(TEXT("电缆5")))
				]
				+SVerticalBox::Slot()
				.AutoHeight()
				[
					SAssignNew(DL_5,SHuanWidget)
					.number(0.351f)
					//.Name(TEXT("烟感"))
				]
			]	
		];
		WD_GridPanel->AddSlot(2,1)
		[
			SNew(SOverlay)
			+SOverlay::Slot()
			[
				SNew(SVerticalBox)
				+SVerticalBox::Slot()
				.HAlign(HAlign_Center)
				.VAlign(VAlign_Center)
				.AutoHeight()
				[
					SNew(STextBlock)
					.Font(MainStyle->FontInfo_Size_12_White)
					.Text(FText::FromString(TEXT("电缆6")))
				]
				+SVerticalBox::Slot()
				.AutoHeight()
				[
					SAssignNew(DL_6,SHuanWidget)
					.number(0.341f)
					//.Name(TEXT("烟感"))
				]
			]	
		];
	}
	
}
END_SLATE_FUNCTION_BUILD_OPTIMIZATION
