// Fill out your copyright notice in the Description page of Project Settings.


#include "UI/Widget/ActorObjectInfo/SDLGZWidget.h"
#include "SlateOptMacros.h"
#include "UI/Style/LFSStyle.h"
#include "UI/Style/MainSlateWidgetStyle.h"
#include "UI/Widget/SLFSProgressbar.h"
#include "UI/Widget/Main/Left/SHuanWidget.h"
#include "Widgets/Images/SImage.h"
#include "Widgets/Layout/SUniformGridPanel.h"

BEGIN_SLATE_FUNCTION_BUILD_OPTIMIZATION
void SDLGZWidget::Construct(const FArguments& InArgs)
{
	MainStyle=&LFSStyle::Get().GetWidgetStyle<FMainSlateStyle>("BPMainStyle");
	
	ChildSlot
	[
		// Populate the widget
		SNew(SBox)
		[
			SNew(SOverlay)
			+SOverlay::Slot()
			[
				SNew(SVerticalBox)
				+SVerticalBox::Slot()
				[
					SNew(SHorizontalBox)
					+SHorizontalBox::Slot()
					[
						SNew(STextBlock)
						.Font(MainStyle->FontInfo_Size_12_White)
						.Text(FText::FromString(TEXT("感知电缆段")))	
					]
					+SHorizontalBox::Slot()
					[
						SNew(STextBlock)
						.Font(MainStyle->FontInfo_Size_12_White)
						.Text(FText::FromString(TEXT("临江门变电站648开关至来福士广场公共开闭所")))	
					]
				]
				+SVerticalBox::Slot()
				[
					SNew(SOverlay)
					+SOverlay::Slot()
					[
						SNew(SImage)
					]
					+SOverlay::Slot()
					[
						SNew(STextBlock)
						.Font(MainStyle->FontInfo_Size_12_White)
						.Text(FText::FromString(TEXT("电缆绝缘在线感知")))
					]
				]
				+SVerticalBox::Slot()
				[
					SNew(SHorizontalBox)
					+SHorizontalBox::Slot()
					[
						SNew(STextBlock)
						.Font(MainStyle->FontInfo_Size_12_White)
						.Text(FText::FromString(TEXT("电缆绝缘评价")))	
					]
					+SHorizontalBox::Slot()
					[
						SNew(STextBlock)
						.Font(MainStyle->FontInfo_Size_12_White)
						.Text(FText::FromString(TEXT("正常")))	
					]
				]
				+SVerticalBox::Slot()
				[
					SNew(STextBlock)
					.Font(MainStyle->FontInfo_Size_12_White)
					.Text(FText::FromString(TEXT("两端电流差值")))
				]
				+SVerticalBox::Slot()
				[
					SNew(SHorizontalBox)
					+SHorizontalBox::Slot()
					[
						SNew(SHorizontalBox)
						+SHorizontalBox::Slot()
						[
							SNew(STextBlock)
							.Font(MainStyle->FontInfo_Size_12_White)
							.Text(FText::FromString(TEXT("A相")))
						]
						+SHorizontalBox::Slot()
						[
							SAssignNew(Progressbar_A,SLFSProgressbar)
							.percent(0.13)
							//.Name(FText::FromString(TEXT("0.13A")))
						]
					]
					+SHorizontalBox::Slot()
					[
						SNew(SHorizontalBox)
						+SHorizontalBox::Slot()
						[
							SNew(STextBlock)
							.Font(MainStyle->FontInfo_Size_12_White)
							.Text(FText::FromString(TEXT("B相")))
						]
						+SHorizontalBox::Slot()
						[
							SAssignNew(Progressbar_B,SLFSProgressbar)
							.percent(0.13)
							//.Name(FText::FromString(TEXT("0.13A")))
						]
					]
					+SHorizontalBox::Slot()
					[
						SNew(SHorizontalBox)
						+SHorizontalBox::Slot()
						[
							SNew(STextBlock)
							.Font(MainStyle->FontInfo_Size_12_White)
							.Text(FText::FromString(TEXT("B相")))
						]
						+SHorizontalBox::Slot()
						[
							SAssignNew(Progressbar_A,SLFSProgressbar)
							.percent(0.27)
							//.Name(FText::FromString(TEXT("0.27A")))
						]
					]
				]
				+SVerticalBox::Slot()
				[
					SNew(SOverlay)
					+SOverlay::Slot()
					[
						SNew(SImage)
					]
					+SOverlay::Slot()
					[
						SNew(STextBlock)
						.Font(MainStyle->FontInfo_Size_12_White)
						.Text(FText::FromString(TEXT("温度接头感知")))
					]
				]
				+SVerticalBox::Slot()
				[
					SNew(SHorizontalBox)
					+SHorizontalBox::Slot()
					[
						SNew(STextBlock)
						.Font(MainStyle->FontInfo_Size_12_White)
						.Text(FText::FromString(TEXT("电缆接头温度评价")))	
					]
					+SHorizontalBox::Slot()
					[
						SNew(STextBlock)
						.Font(MainStyle->FontInfo_Size_12_White)
						.Text(FText::FromString(TEXT("正常")))	
					]
				]

				+SVerticalBox::Slot()
				[
					SNew(SOverlay)
					+SOverlay::Slot()
					[
						SNew(SImage)
					]
					+SOverlay::Slot()
					[
						SNew(STextBlock)
						.Font(MainStyle->FontInfo_Size_12_White)
						.Text(FText::FromString(TEXT("温度接头感知")))
					]
				]
				+SVerticalBox::Slot()
				[
					SAssignNew(WD_GridPanel,SUniformGridPanel)
				]
				+SVerticalBox::Slot()
				[
					SNew(SHorizontalBox)
					+SHorizontalBox::Slot()
					[
						SNew(STextBlock)
						.Font(MainStyle->FontInfo_Size_12_White)
						.Text(FText::FromString(TEXT("各电缆井位电缆震动感知")))	
					]
					+SHorizontalBox::Slot()
					[
						SNew(STextBlock)
						.Font(MainStyle->FontInfo_Size_12_White)
						.Text(FText::FromString(TEXT("正常")))	
					]
				]
			]
		]
	];
	if (WD_GridPanel)
	{
		WD_GridPanel->AddSlot(0,0)
		[
			SNew(SOverlay)
			+SOverlay::Slot()
			[
				SNew(SVerticalBox)
				+SVerticalBox::Slot()
				[
					SNew(STextBlock)
					.Font(MainStyle->FontInfo_Size_12_White)
					.Text(FText::FromString(TEXT("电缆1")))
				]
				+SVerticalBox::Slot()
				[
					SAssignNew(DL_1,SHuanWidget)
					.number(0.325f)
					//.Name(TEXT("烟感"))
				]
			]	
		];
		WD_GridPanel->AddSlot(1,0)
		[
			SNew(SOverlay)
			+SOverlay::Slot()
			[
				SNew(SVerticalBox)
				+SVerticalBox::Slot()
				[
					SNew(STextBlock)
					.Font(MainStyle->FontInfo_Size_12_White)
					.Text(FText::FromString(TEXT("电缆2")))
				]
				+SVerticalBox::Slot()
				[
					SAssignNew(DL_2,SHuanWidget)
					.number(0.341f)
					//.Name(TEXT("烟感"))
				]
			]	
		];
		WD_GridPanel->AddSlot(2,0)
		[
			SNew(SOverlay)
			+SOverlay::Slot()
			[
				SNew(SVerticalBox)
				+SVerticalBox::Slot()
				[
					SNew(STextBlock)
					.Font(MainStyle->FontInfo_Size_12_White)
					.Text(FText::FromString(TEXT("电缆3")))
				]
				+SVerticalBox::Slot()
				[
					SAssignNew(DL_3,SHuanWidget)
					.number(0.337f)
					//.Name(TEXT("烟感"))
				]
			]	
		];
		WD_GridPanel->AddSlot(1,0)
		[
			SNew(SOverlay)
			+SOverlay::Slot()
			[
				SNew(SVerticalBox)
				+SVerticalBox::Slot()
				[
					SNew(STextBlock)
					.Font(MainStyle->FontInfo_Size_12_White)
					.Text(FText::FromString(TEXT("电缆4")))
				]
				+SVerticalBox::Slot()
				[
					SAssignNew(DL_4,SHuanWidget)
					.number(0.332f)
					//.Name(TEXT("烟感"))
				]
			]	
		];
		WD_GridPanel->AddSlot(1,1)
		[
			SNew(SOverlay)
			+SOverlay::Slot()
			[
				SNew(SVerticalBox)
				+SVerticalBox::Slot()
				[
					SNew(STextBlock)
					.Font(MainStyle->FontInfo_Size_12_White)
					.Text(FText::FromString(TEXT("电缆5")))
				]
				+SVerticalBox::Slot()
				[
					SAssignNew(DL_5,SHuanWidget)
					.number(0.351f)
					//.Name(TEXT("烟感"))
				]
			]	
		];
		WD_GridPanel->AddSlot(1,2)
		[
			SNew(SOverlay)
			+SOverlay::Slot()
			[
				SNew(SVerticalBox)
				+SVerticalBox::Slot()
				[
					SNew(STextBlock)
					.Font(MainStyle->FontInfo_Size_12_White)
					.Text(FText::FromString(TEXT("电缆6")))
				]
				+SVerticalBox::Slot()
				[
					SAssignNew(DL_6,SHuanWidget)
					.number(0.341f)
					//.Name(TEXT("烟感"))
				]
			]	
		];
	}
	
}
END_SLATE_FUNCTION_BUILD_OPTIMIZATION
