// Fill out your copyright notice in the Description page of Project Settings.


#include "UI/Widget/TongDao/STDGZWidget.h"
#include "SlateOptMacros.h"
#include "UI/Style/LFSStyle.h"
#include "UI/Style/MainSlateWidgetStyle.h"
#include "Widgets/Images/SImage.h"

BEGIN_SLATE_FUNCTION_BUILD_OPTIMIZATION
void STDGZWidget::Construct(const FArguments& InArgs)
{
	MainStyle=&LFSStyle::Get().GetWidgetStyle<FMainSlateStyle>("BPMainStyle");
	ChildSlot
	[
		// Populate the widget
		SNew(SOverlay)
		+SOverlay::Slot()
		[
			SNew(SBox)
			.Padding(FMargin(900,200,500,200))
			[
				SNew(SOverlay)
				+SOverlay::Slot()
				[
					SNew(SImage)
					.Image(&MainStyle->Center_Window1)
				]
				+SOverlay::Slot()
				.VAlign(VAlign_Top)
				.HAlign(HAlign_Left)
				.Padding(FMargin(40,-32,0,0))
				[
					SNew(SOverlay)
					+SOverlay::Slot()
					.VAlign(VAlign_Center)
					.HAlign(HAlign_Center)
					[
						SNew(SImage)
						.Image(&MainStyle->TD_LB)
					]
					+SOverlay::Slot()
					.VAlign(VAlign_Center)
					.HAlign(HAlign_Center)
					[
						SNew(STextBlock)
						.Font(MainStyle->FontInfo_Size_16_White)
						.Text(FText::FromString(TEXT("通道感知")))
					]
				]
				+SOverlay::Slot()
				.Padding(FMargin(30))
				[
					SNew(SBorder)
					[
						SNew(SVerticalBox)
						+SVerticalBox::Slot()
						.AutoHeight()
						[
							SNew(SHorizontalBox)
							+SHorizontalBox::Slot()
							.AutoWidth()
							[
								SNew(SBorder)
								[
									SNew(STextBlock)
									.Font(MainStyle->FontInfo_Size_12_White)
									.Text(FText::FromString(TEXT("当前时间")))
								]
									
							]
							+SHorizontalBox::Slot()
							//.Padding(FMargin(2))
							[
								SNew(SBorder)
								.Padding(FMargin(5,0,0,0))
								[
									SNew(STextBlock)
									.Font(MainStyle->FontInfo_Size_12_White)
									.Text(FText::FromString(TEXT("获取系统时间:Time")))
								]
									
							]
						]
						+SVerticalBox::Slot()
						.AutoHeight()
						[
							SNew(SHorizontalBox)
							+SHorizontalBox::Slot()
							.AutoWidth()
							[
								SNew(SBorder)
								[
									SNew(STextBlock)
									.Font(MainStyle->FontInfo_Size_12_White)
									.Text(FText::FromString(TEXT("当前地点")))
								]	
							]
							+SHorizontalBox::Slot()
							[
								SNew(SBorder)
								.Padding(FMargin(5,0,0,0))
								[
									SNew(STextBlock)
									.Font(MainStyle->FontInfo_Size_12_White)
									.Text(FText::FromString(TEXT("Location")))
								]
									
							]
						]
						+SVerticalBox::Slot()
						.AutoHeight()
						[
							SNew(SHorizontalBox)
							+SHorizontalBox::Slot()
							.AutoWidth()
							[
								SNew(SBorder)[
								SNew(STextBlock)
								.Font(MainStyle->FontInfo_Size_12_White)
								.Text(FText::FromString(TEXT("环境温度")))	

								]
							]
							+SHorizontalBox::Slot()
							[
								
							SNew(SBorder)
							.Padding(FMargin(5,0,0,0))
							[
								SNew(STextBlock)
								.Font(MainStyle->FontInfo_Size_12_White)
								.Text(FText::FromString(TEXT("27.3℃")))	
							]
							]
						]
						+SVerticalBox::Slot()
						.AutoHeight()
						[
							
							SNew(SHorizontalBox)
							+SHorizontalBox::Slot()
							.AutoWidth()
							[
								SNew(SBorder)
								[
									SNew(STextBlock)
									.Font(MainStyle->FontInfo_Size_12_White)
									.Text(FText::FromString(TEXT("水位监测")))	
								]
							]
							+SHorizontalBox::Slot()
							[
								SNew(SBorder)
								.Padding(FMargin(5,0,0,0))
								[
									SNew(STextBlock)
									.Font(MainStyle->FontInfo_Size_12_White)
									.Text(FText::FromString(TEXT("0.12米")))	
								]
							]
						]
						+SVerticalBox::Slot()
						.AutoHeight()
						[
							SNew(SHorizontalBox)
							+SHorizontalBox::Slot()
							.AutoWidth()
							[
								SNew(SBorder)
								[
									SNew(STextBlock)
									.Font(MainStyle->FontInfo_Size_12_White)
									.Text(FText::FromString(TEXT("烟感监测")))
								]
							]
							+SHorizontalBox::Slot()
							[
								SNew(SBorder)
								.Padding(FMargin(5,0,0,0))
								[
									SNew(STextBlock)
									.Font(MainStyle->FontInfo_Size_12_White)
									.Text(FText::FromString(TEXT("正常")))
								]
							]
						]
						+SVerticalBox::Slot()
						.AutoHeight()
						[
							SNew(SHorizontalBox)
							+SHorizontalBox::Slot()
							.AutoWidth()
							[
								SNew(SBorder)
								[
									SNew(STextBlock)
									.Font(MainStyle->FontInfo_Size_12_White)
									.Text(FText::FromString(TEXT("井盖监测")))
								]
							]
							+SHorizontalBox::Slot()
							[
								SNew(SBorder)
								.Padding(FMargin(5,0,0,0))
								[
									SNew(STextBlock)
									.Font(MainStyle->FontInfo_Size_12_White)
									.Text(FText::FromString(TEXT("关闭")))
								]
							]
						]
						+SVerticalBox::Slot()
						.AutoHeight()
						[
							SNew(SHorizontalBox)
							+SHorizontalBox::Slot()
							.AutoWidth()
							[
								SNew(SBorder)
								[
									SNew(STextBlock)
									.Font(MainStyle->FontInfo_Size_12_White)
									.Text(FText::FromString(TEXT("外破监测")))
								]
									
							]
							+SHorizontalBox::Slot()
							[
								SNew(SBorder)
								.Padding(FMargin(5,0,0,0))
								[
									SNew(STextBlock)
									.Font(MainStyle->FontInfo_Size_12_White)
									.Text(FText::FromString(TEXT("正常")))
								]
									
							]
						]
						+SVerticalBox::Slot()
						.AutoHeight()
						[
							SNew(SHorizontalBox)
							+SHorizontalBox::Slot()
							.AutoWidth()
							[
								SNew(SBorder)
								[
									SNew(STextBlock)
									.Font(MainStyle->FontInfo_Size_12_White)
									.Text(FText::FromString(TEXT("入侵警告")))
								]
							]
							+SHorizontalBox::Slot()
							[
								SNew(SBorder)
								.Padding(FMargin(5,0,0,0))
								[
									SNew(STextBlock)
									.Font(MainStyle->FontInfo_Size_12_White)
									.Text(FText::FromString(TEXT("无")))	
								]
							]
						]
						+SVerticalBox::Slot()
						.AutoHeight()
						[
							
							SNew(SOverlay)
							+SOverlay::Slot()
							.Padding(0,0,0,0)
							[
								SNew(SBox)
								[
									SNew(SImage)
									.Image(&MainStyle->Main_Right_Infotitle)
								]
							]
							+SOverlay::Slot()
							.Padding(0,0,0,0)
							[
								SNew(SHorizontalBox)
								+SHorizontalBox::Slot()
								.HAlign(HAlign_Center)
								.VAlign(VAlign_Center)
								[
									SNew(STextBlock)
									.Font(MainStyle->FontInfo_Size_12_White)
									.Text(FText::FromString(TEXT("监控画面")))
								]
							]
						]	
						+SVerticalBox::Slot()
						[
							SNew(SImage)
							.Image(&MainStyle->Main_Window)
							
						]
					]
				]
			]
		]
	];
	
}
END_SLATE_FUNCTION_BUILD_OPTIMIZATION
